import React from 'react'; // Added to resolve React.FC type issues
import { AdminPermission, BadgeType, DashboardWidgetConfig, DashboardWidgetType, FAQItem, PlatformSettingKey, CalendarEventType, AccentPaletteKey, InterfaceDensity, GlossaryTermItem, TransactionType, GoalType, BetType, BetStatus, Role } from "./types";
// FIX: Corrected imports for all icons, including new ones and custom aliases.
import { 
    FirstProfitIcon, PlatformVeteranIcon, MilestoneInvestmentIcon, HighRollerIcon, SparklesIcon as DefaultBadgeIcon, 
    CogIcon, ChartBarIcon, PresentationChartLineIcon, ChartBarSquareIcon, GiftIcon, SparklesIcon, CalendarDaysIcon, 
    QuestionMarkCircleIcon, TableCellsIcon, FlagIcon, TrophyIcon, CurrencyEuroIcon, FilterIcon, DocumentChartBarIcon, 
    UserGroupIcon, CheckBadgeIcon, BookOpenIcon, BanknotesIcon
} from "./components/ui/Icons";

// Adresa de bază a noului API. Presupune că fișierul data.php se află într-un folder 'api' la rădăcina site-ului.
const API_BASE_URL = '/api/data.php';

// Noile endpoint-uri pentru a prelua datele din baza de date prin scriptul PHP.
export const API_ENDPOINTS = {
  globalStats: `${API_BASE_URL}?endpoint=globalStats`,
  users: `${API_BASE_URL}?endpoint=users`,
  transactions: `${API_BASE_URL}?endpoint=transactions`,
  dailyHistory: `${API_BASE_URL}?endpoint=dailyHistory`,
  announcements: `${API_BASE_URL}?endpoint=announcements`,
  userMessages: `${API_BASE_URL}?endpoint=userMessages`,
  investmentAlerts: `${API_BASE_URL}?endpoint=investmentAlerts`,
  feedback: `${API_BASE_URL}?endpoint=feedback`,
  platformSettings: `${API_BASE_URL}?endpoint=platformSettings`,
  referrals: `${API_BASE_URL}?endpoint=referrals`,
  calendarEvents: `${API_BASE_URL}?endpoint=calendarEvents`,
  investmentGoals: `${API_BASE_URL}?endpoint=investmentGoals`,
  bets: `${API_BASE_URL}?endpoint=bets`,
};

// FIX: Added GITHUB_DATA_URLS which was missing. It's referenced for initial platform settings.
// These URLs are likely legacy/placeholders as data fetching now uses API_ENDPOINTS.
const GITHUB_BASE_REPO_URL = 'https://raw.githubusercontent.com/your-username/your-repo/main/data';
export const GITHUB_DATA_URLS = {
  globalStats: `${GITHUB_BASE_REPO_URL}/globalStats.json`,
  users: `${GITHUB_BASE_REPO_URL}/users.json`,
  transactions: `${GITHUB_BASE_REPO_URL}/transactions.json`,
  dailyHistory: `${GITHUB_BASE_REPO_URL}/dailyHistory.json`,
  bets: `${GITHUB_BASE_REPO_URL}/bets.json`,
};
            
export const DEFAULT_AVATAR_URL = 'https://picsum.photos/seed/default/100/100';
export const NOTIFICATION_TIMEOUT = 5000; // ms
export const APP_VERSION = "1.5.0"; // Application version incremented

export const ADMIN_TELEGRAM_USERNAME_FALLBACK = "Pariaza_Inteligent";
export const TELEGRAM_PREDEFINED_MESSAGE_FALLBACK = "Bună ziua, aș dori să îmi creez un cont pe platforma Banca Comună de Investiții și am nevoie de ajutor.";

export const UI_TEXT_ROMANIAN = {
  appName: "Banca Comună de Investiții",
  tagline: "Pariaza Inteligent",
  homepageWelcomeMessage: "Platforma ta dedicată pentru investiții inteligente în pariuri sportive. Maximizează-ți potențialul alături de o comunitate de investitori avizați.",
  loadingApp: "Se încarcă aplicația...",
  login: "Autentificare",
  email: "Email",
  password: "Parolă",
  loginButton: "Intră în cont",
  logoutButton: "Deconectare",
  authenticationFailed: "Autentificare eșuată. Verifică datele.",
  accessDenied: "Acces Interzis",
  loginPageContactHelp: "Nu ai cont sau ai întâmpinat probleme?",
  contactAdminTelegramButton: "Contactează Admin pe Telegram",
  home: "Acasă",
  howItWorks: "Cum funcționează",
  statistics: "Statistici",
  trophyRoom: "Sala Trofeelor",
  investments: "Investiții",
  withdrawals: "Retrageri",
  profile: "Profil",
  configureAlerts: "Configurare Alerte", 
  cycleReports: "Rapoarte Ciclice", 
  advancedReports: "Rapoarte Detaliate", 
  notificationCenter: "Centru Notificări",
  helpCenter: "Centru Ajutor", 
  submitFeedback: "Trimite Feedback", 
  myReferrals: "Recomandările Mele", 
  myGoals: "Obiectivele Mele",
  betHistory: "Istoric Pariuri",
  userPanel: "Panou Utilizator",
  adminPanel: "Panou Admin",
  adminDashboard: "Dashboard Admin",
  adminMarketPulse: "Pulsul Pieței (AI)",
  manageUsers: "Gestionare Utilizatori",
  manageAnnouncements: "Gestionare Anunțuri",
  dataManagement: "Management Date",
  pendingRequests: "Cereri în Așteptare",
  systemLog: "Jurnal Sistem",
  viewFeedback: "Feedback Utilizatori", 
  platformSettings: "Setări Platformă", 
  backtestingStrategies: "Testare Strategii (Backtest)", 
  adminCalendar: "Calendar Evenimente",
  save: "Salvează",
  cancel: "Anulează",
  edit: "Modifică",
  delete: "Șterge",
  confirm: "Confirmă",
  close: "Închide",
  error: "Eroare",
  success: "Succes",
  warning: "Atenție",
  info: "Info",
  noDataAvailable: "Nu există date disponibile.",
  areYouSure: "Ești sigur?",
  actionCannotBeUndone: "Această acțiune nu poate fi anulată.",
  myDashboard: "Dashboard-ul Meu",
  investedAmount: "Suma Investită",
  totalProfit: "Profit Total Acumulat",
  totalBalance: "Sold Total Curent", 
  currentProfit: "Profit Ciclu Actual",
  grossProfit: "Profit Brut",
  platformFee: "Taxă Platformă (Ciclu Actual)",
  netProfit: "Profit Net",
  requestInvestment: "Cere Investiție",
  requestWithdrawal: "Cere Retragere",
  platformFeePaidCumulativeInfo: "Suma totală a taxelor de platformă reținute din profitul brut în ciclul curent.",
  platformFeeLiveRateInfo: "Rata curentă a taxei de platformă (aplicabilă profiturilor viitoare):",
  platformFeeLiveRateReason: "Motiv: Numărul actual de {activeInvestorsCount} investitori activi corespunde nivelului: '{tierDescription}'.",
  currentCycleDetails: "Detalii Ciclu Curent:",
  currentCycleGrossProfitLabel: "Profit Brut (Est.):",
  currentCycleNetProfitLabel: "Profit Net (Est.):",
  noCurrentCycleProfit: "Niciun profit înregistrat pentru ciclul curent.",
  userDashboardChartTitle: "Evoluția Profitului Tău Personal",
  userDashboardChartLabel: "Profit Personal (Cumulativ)",
  userProfitShareTitle: "Ponderea Ta din Profitul Băncii",
  userProfitShareDescription: "Acest procent reprezintă cota ta din profitul total generat de bancă, înainte de aplicarea taxei de platformă, bazată pe investiția ta curentă în raport cu totalul investițiilor active.",
  userProfitShareValueLabel: "Procentul tău din total investiții:",
  userDashboardFundGrowthChartTitle: "Evoluția Valorii Fondului Tău", 
  userDashboardFundGrowthPercentageTitle: "Creștere Fond (%)", 
  userDashboardShowTotalFundValueLabel: "Afișează Valoare Totală Fond",
  userDashboardShowInvestedAmountLabel: "Afișează Suma Investită (Cumulativ)",
  userDashboardShowAccumulatedProfitLabel: "Afișează Profit Acumulat (Cumulativ)",
  userDashboardShowPersonalProfitLabel: "Afișează Profit Personal (Cumulativ)",
  financialProjectionsTitle: "Proiecții Financiare Interactive",
  hypotheticalInvestmentLabel: "Suma Investiție Simulare (EUR)",
  performanceScenarioLabel: "Scenariu Performanță",
  scenarioConservative: "Conservator (0.25% creștere medie zilnică brută)",
  scenarioModerate: "Moderat (0.5% creștere medie zilnică brută)",
  scenarioOptimistic: "Optimist (1.0% creștere medie zilnică brută)",
  scenarioCustom: "Personalizat",
  customDailyGrossROILabel: "Rată de Creștere Zilnică Brută (%)",
  projectionPeriodLabel: "Perioadă Proiecție (zile)",
  calculateProjectionButton: "Calculează Proiecția",
  projectionResultsTitle: "Rezultate Proiecție:",
  projectedGrossProfitLabel: "Profit Brut Proiectat",
  projectedPlatformFeeLabel: "Taxă Platformă Proiectată",
  projectedNetProfitLabel: "Profit Net Proiectat",
  projectedFinalBalanceLabel: "Sold Final Proiectat",
  projectionDisclaimer: "Aceste proiecții sunt estimări bazate pe ipotezele selectate și nu reprezintă o garanție a performanței viitoare. Taxa de platformă utilizată în simulare este rata curentă.",
  invalidProjectionInput: "Te rog introdu valori valide pentru simulare.",
  geminiAdvancedAnalysisTitle: "Analiză Predictivă Avansată cu Gemini",
  geminiAnalysisInvestmentLabel: "Suma pentru Analiză (EUR)",
  geminiAnalysisPeriodLabel: "Perioada pentru Analiză (zile)",
  geminiUserQueryLabel: "Descrie scenariul sau întrebarea ta pentru Gemini:",
  geminiUserQueryPlaceholder: "Ex: Cum ar putea evolua investiția mea în X luni dacă randamentul mediu zilnic este Y% dar apar și Z zile cu pierderi?",
  generateGeminiAnalysisButton: "Generează Analiză cu Gemini",
  geminiAnalysisResultTitle: "Rezultatul Analizei Gemini:",
  geminiAnalysisLoading: "Gemini procesează analiza avansată...",
  geminiProjectionDisclaimer: "Această analiză este generată de un model AI (Gemini) și are scop informativ. Nu constituie consultanță financiară și nu reprezintă o garanție a rezultatelor viitoare. Verifică întotdeauna informațiile și ia decizii informate.",
  geminiApiKeyMissing: "Cheia API pentru Gemini nu este configurată. Funcționalitatea de analiză avansată nu este disponibilă.",
  geminiAnalysisError: "A apărut o eroare la generarea analizei Gemini. Te rugăm să încerci mai târziu.",
  geminiPromptTooShort: "Te rog introdu o întrebare sau un scenariu mai detaliat pentru Gemini.",
  generateAiPerformanceReport: "Generează Raport de Performanță AI",
  geminiMarketPulseTitle: "Pulsul Pieței - Analiză AI a Performanței",
  geminiMarketPulseDescription: "Obține o sinteză strategică generată de AI despre ce funcționează și ce nu, pe baza istoricului de pariuri finalizate.",
  geminiMarketPulseReportTitle: "Pulsul Pieței - Analiză AI a Performanței",
  geminiMarketPulseReportDescription: "Generează un raport detaliat cu grafice și analize textuale despre performanța istorică a pariurilor, folosind puterea AI Gemini.",
  generateMarketPulseReport: "Generează Raport Pulsul Pieței",
  marketPulseAnalysisInProgress: "Gemini analizează performanța istorică și construiește raportul... Acest proces poate dura câteva momente.",
  geminiAiReportLoading: "Gemini analizează performanța istorică... Acest proces poate dura câteva momente.",
  geminiAiReportResultTitle: "Sinteză AI (Pulsul Pieței)",
  noBetsForAnalysis: "Nu există suficiente pariuri finalizate (minim 10) pentru a genera un raport de performanță relevant.",
  interactiveFeeSimulatorTitle: "Simulator Interactiv Comision Platformă",
  feeSimulatorDescription: "Înțelege cum funcționează comisionul dinamic al platformei. Modifică valorile de mai jos pentru a vedea cum se calculează taxa și profitul tău net.",
  simulatedInvestorsLabel: "Număr Simulat de Investitori Activi",
  simulatedGrossProfitLabel: "Profit Brut Personal Simulat (EUR)",
  resultingFeeRateLabel: "Rata de Comision Rezultată",
  estimatedPlatformFeeLabel: "Comision Platformă Estimat",
  estimatedNetProfitLabel: "Profitul Tău Net Estimat",
  feeTierDescriptionLabel: "Nivel Taxă",
  createNewUser: "Crează Utilizator Nou",
  createNewAdmin: "Crează Admin Nou",
  userName: "Nume Utilizator",
  userRole: "Rol Utilizator",
  selectRole: "Selectează Rol",
  roleAdmin: "Admin",
  roleUser: "Investitor",
  initialInvestment: "Investiție Inițială",
  referralCodeOptional: "Cod de Recomandare (Opțional)", 
  userCreatedSuccessfully: "Utilizator creat cu succes. Fișierul users.json a fost descărcat.",
  userUpdatedSuccessfully: "Utilizator actualizat cu succes. Fișierul users.json a fost descărcat.",
  userDeletedSuccessfully: "Utilizator șters cu succes. Fișierul users.json a fost descărcat.",
  failedToCreateUser: "Crearea utilizatorului a eșuat.",
  failedToUpdateUser: "Actualizarea utilizatorului a eșuat.",
  failedToDeleteUser: "Ștergerea utilizatorului a eșuat.",
  confirmUserDeletionTitle: "Confirmă Ștergerea Utilizatorului",
  confirmUserDeletionMessage: "Ești sigur că vrei să ștergi utilizatorul {userName} ({userEmail})? Această acțiune este ireversibilă și va elimina utilizatorul din sistem.",
  sendMessageToSelectedUsers: "Trimite Mesaj ({count})",
  sendMessageModalTitle: "Trimite Mesaj către {count} Utilizator(i)",
  messageTitleLabel: "Titlu Mesaj",
  messageContentLabel: "Conținut Mesaj",
  sendMessageButton: "Trimite Mesaj",
  adminMessageHistory: "Istoric Mesaje Admin",
  noAdminMessages: "Nu ai mesaje de la administrator.",
  cannotDeleteSelf: "Nu te poți șterge singur.",
  cannotDeleteGlobalAdmin: "Administratorul global nu poate fi șters.",
  managePermissions: "Gestionare Permisiuni (Admin)",
  permissionStateActive: "Activ",
  permissionStateInactive: "Inactiv",
  userIsActive: "Cont Activ",
  userIsInactive: "Cont Inactiv",
  initialPassword: "Parolă Inițială",
  passwordHelpText: "Parola nu poate fi modificată ulterior din acest panou. Implementați o funcție separată de resetare parolă dacă este necesar.",
  betManagementTitle: "Management Pariuri",
  addNewBet: "Adaugă Pariu Nou",
  closeDayTitle: "Închidere Zi și Distribuire Profit",
  closeDayDescription: "Selectează data pentru care dorești să finalizezi pariurile rezolvate. Sistemul va calcula automat profitul brut total, va crea o nouă înregistrare în istoricul zilnic și va distribui profitul net către investitori.",
  selectDateForClosure: "Selectează Data",
  closeDayAndDistribute: "Închide Ziua & Distribuie Profit",
  noUnprocessedBets: "Nu există pariuri rezolvate și neprocesate pentru data selectată.",
  confirmBetDeletionTitle: "Confirmă Ștergerea Pariului",
  confirmBetDeletionMessage: "Ești sigur că vrei să ștergi acest pariu? Acțiunea este ireversibilă.",
  resolveBetTitle: "Rezolvă Pariu",
  confirmResolveBetMessage: "Ești sigur că vrei să marchezi acest pariu ca '{status}'? Profitul calculat va fi: {profit}.",
  betSportLabel: "Sport",
  betLeagueLabel: "Ligă/Competiție",
  betEventLabel: "Eveniment",
  betMarketLabel: "Piață",
  betSelectionLabel: "Selecție",
  betOddsLabel: "Cotă",
  betStakeLabel: "Miză (EUR)",
  betTypeLabel: "Tip Pariu",
  betNotesLabel: "Notițe (Opțional)",
  generateMiddleSuggestions: "Generează Sugestii Middle (AI)",
  importJSON: "Importă JSON",
  exportJSON: "Exportă JSON",
  exportGlobalStats: "Exportă Statistici Globale",
  exportUsers: "Exportă Utilizatori",
  exportTransactions: "Exportă Tranzacții",
  exportDailyHistory: "Exportă Istoric Zilnic",
  exportAnnouncements: "Exportă Anunțuri",
  exportUserMessages: "Exportă Mesaje Utilizatori",
  exportInvestmentAlerts: "Exportă Alerte Investiții", 
  exportFeedback: "Exportă Feedback", 
  exportPlatformSettings: "Exportă Setări Platformă", 
  exportReferrals: "Exportă Recomandări", 
  exportCalendarEvents: "Exportă Evenimente Calendar", 
  exportInvestmentGoals: "Exportă Obiective Investiții",
  exportBets: "Exportă Pariuri",
  importGlobalStats: "Importă Statistici Globale",
  importUsers: "Importă Utilizatori",
  importTransactions: "Importă Tranzacții",
  importDailyHistory: "Importă Istoric Zilnic",
  importAnnouncements: "Importă Anunțuri",
  importUserMessages: "Importă Mesaje Utilizatori",
  importInvestmentAlerts: "Importă Alerte Investiții", 
  importFeedback: "Importă Feedback",
  importPlatformSettings: "Importă Setări Platformă", 
  importReferrals: "Importă Recomandări", 
  importCalendarEvents: "Importă Evenimente Calendar",
  importInvestmentGoals: "Importă Obiective Investiții",
  importBets: "Importă Pariuri",
  fileImportedSuccessfully: "Fișier importat cu succes.",
  fileExportedSuccessfully: "Fișier exportat cu succes.",
  failedToImportFile: "Importul fișierului a eșuat.",
  failedToExportFile: "Exportul fișierului a eșuat.",
  dailyProfit: "Profit Zilnic Brut",
  turnover: "Turnover",
  numberOfBets: "Nr. Pariuri",
  updateDailyData: "Actualizează Date Zilnice",
  approve: "Aprobă",
  reject: "Respinge",
  pendingInvestmentRequests: "Cereri de Investiție în Așteptare",
  pendingWithdrawalRequests: "Cereri de Retragere în Așteptare",
  requestApproved: "Cerere aprobată.",
  requestRejected: "Cerere respinsă.",
  editProfile: "Modifică Profil",
  avatarURL: "URL Avatar",
  updateProfile: "Actualizează Profil",
  profileUpdated: "Profil actualizat.",
  profileExportCardTitle: "Export Istoric Tranzacții",
  exportTransactionsCsvButton: "Exportă Istoric (CSV)",
  exportTransactionsPdfButton: "Exportă Istoric (PDF)",
  exportPdfThemeLabel: "Temă PDF Istoric",
  exportGeneratingCsv: "Se generează CSV...",
  exportGeneratingPdf: "Se generează PDF...",
  exportCsvSuccess: "Istoricul tranzacțiilor (CSV) a fost generat.",
  exportPdfSuccess: "Istoricul tranzacțiilor (PDF) a fost generat.",
  exportError: "Eroare la generarea exportului.",
  installApp: "Instalează Aplicația",
  lightMode: "Mod Luminos",
  darkMode: "Mod Întunecat",
  themeCustomizationTitle: "Personalizare Interfață",
  accentColorLabel: "Culoare de Accent Secundară",
  interfaceDensityLabel: "Densitate Interfață",
  densityComfortable: "Confortabil",
  densityCompact: "Compact",
  themePreferencesSaved: "Preferințele de interfață au fost salvate.",
  failedToSaveThemePreferences: "Salvarea preferințelor de interfață a eșuat.",
  fetchDataError: "Eroare la preluarea datelor de la API. Verifică scriptul PHP și conexiunea la baza de date.",
  githubDataDisclaimer: "Datele sunt preluate de pe GitHub. Asigură-te că URL-urile sunt corect configurate în fișierul constants.ts. Pentru persistența modificărilor efectuate în aplicație (ex: adăugare utilizator, aprobare cerere), exportă datele modificate și actualizează manual fișierele JSON corespunzătoare în repository-ul tău GitHub.",
  refreshData: "Reîmprospătează Datele",
  dataRefreshed: "Datele au fost reîmprospătate de la API.",
  geminiAiAnalysis: "Analiză Inteligentă cu Gemini",
  geminiPromptLabel: "Întrebarea sau solicitarea ta pentru Gemini:",
  geminiSubmitButton: "Trimite la Gemini",
  geminiLoading: "Gemini procesează cererea...",
  geminiDisclaimer: "Analiza oferită de Gemini este generată automat și are scop informativ. Nu reprezintă sfaturi financiare directe. Verifică întotdeauna informațiile.",
  geminiApiError: "Eroare la comunicarea cu API-ul Gemini. Te rugăm să încerci mai târziu.",
  geminiContextIntro: "Pe baza următoarelor date despre fond și a întrebării tale, Gemini va oferi o analiză.",
  geminiBetRiskAnalysisTitle: "Recomandări Pariuri și Analiză de Risc (Gemini)",
  potentialBetSportEventLabel: "Sport/Eveniment",
  potentialBetTypeLabel: "Tip Pariu",
  potentialBetOddsLabel: "Cotă",
  potentialBetStakeLabel: "Miză (unități/EUR)",
  addPotentialBetButton: "Adaugă Pariu la Listă",
  potentialBetsListTitle: "Listă Pariuri Potențiale pentru Analiză și Recomandare:",
  removeBetButton: "Elimină",
  noPotentialBets: "Niciun pariu adăugat pentru analiză.",
  additionalObservationsLabel: "Observații/Preferințe de Risc pentru Gemini (opțional):",
  analyzePortfolioRiskButton: "Obține Recomandări și Analiză de Risc (Gemini)",
  geminiBetAnalysisResultTitle: "Recomandări și Analiză de Risc (Gemini):",
  geminiBetAnalysisLoading: "Gemini generează recomandări și analizează riscul...",
  geminiBetRiskDisclaimer: "Aceste recomandări și analize sunt generate de un model AI (Gemini) și au scop informativ. Nu constituie consultanță financiară sau de pariere și nu garantează rezultate. Deciziile finale de pariere aparțin administratorului.",
  potentialBetMissingFields: "Toate câmpurile (Sport, Tip, Cotă, Miză) sunt obligatorii pentru un pariu.",
  potentialBetInvalidNumbers: "Cota și Miza trebuie să fie numere valide, pozitive.",
  chartLabelCumulativeGrossProfit: "Profit Brut (Cumulativ)",
  chartLabelCumulativeBankValue: "Valoare Bancă (Cumulativ)",
  chartLabelDailyGrossProfit: "Profit Brut Zilnic", 
  chartLabelBankValueEndOfDay: "Valoare Bancă (Final de Zi)",
  customizeChartButton: "Personalizează Grafic",
  seriesVisibility: "Vizibilitate Serii:",
  chartType: "Tip Grafic:",
  lineChart: "Linie",
  barChart: "Bare",
  showCumulativeGrossProfit: "Profit Brut (Cumulativ)",
  showCumulativeBankValue: "Valoare Bancă (Cumulativ)",
  showDailyGrossProfit: "Profit Brut Zilnic", 
  zoomAndPanInfo: "Utilizează rotița mouse-ului/pinch pentru zoom și click-and-drag pentru pan.",
  filterByDateRange: "Filtrează după intervalul de date:",
  selectPeriod: "Selectează perioada",
  last7Days: "Ultimele 7 zile",
  last30Days: "Ultimele 30 de zile",
  currentMonth: "Luna curentă",
  currentYear: "Anul curent",
  allTime: "Toată perioada",
  customRange: "Interval personalizat",
  startDate: "Dată început",
  endDate: "Dată sfârșit",
  applyFilter: "Aplică filtru",
  invalidDateRange: "Interval de date invalid. Data de început trebuie să fie anterioară datei de sfârșit.",
  announcementsTab: "Anunțuri",
  personalMessagesTab: "Mesaje Personale",
  markAsRead: "Marchează ca citit",
  markAllAsRead: "Marchează toate ca citite",
  noAnnouncements: "Nu există anunțuri momentan.",
  noPersonalMessages: "Nu ai mesaje personale noi.",
  viewDetails: "Vezi detalii",
  unreadMessages: "Mesaje necitite",
  createNewAnnouncement: "Crează Anunț Nou",
  announcementTitle: "Titlu Anunț",
  announcementContent: "Conținut Anunț",
  announcementImportance: "Importanță",
  importanceHigh: "Ridicat",
  importanceMedium: "Mediu",
  importanceLow: "Scăzut",
  announcementCreatedSuccessfully: "Anunț creat cu succes.",
  announcementUpdatedSuccessfully: "Anunț actualizat cu succes.",
  announcementDeletedSuccessfully: "Anunț șters cu succes.",
  failedToCreateAnnouncement: "Crearea anunțului a eșuat.",
  failedToUpdateAnnouncement: "Actualizarea anunțului a eșuat.",
  failedToDeleteAnnouncement: "Ștergerea anunțului a eșuat.",
  confirmAnnouncementDeletionTitle: "Confirmă Ștergerea Anunțului",
  confirmAnnouncementDeletionMessage: "Ești sigur că vrei să ștergi acest anunț? Acțiunea este ireversibilă.",
  userAlertsTitle: "Alerte de Profit/Pierdere",
  createNewAlert: "Crează Alertă Nouă",
  alertType: "Tip Alertă",
  thresholdValue: "Valoare Prag",
  alertValueType: "Tip Valoare Prag",
  valueTypePercentage: "Procent (%)",
  valueTypeAmount: "Sumă (EUR)",
  alertConditionProfitGainPercent: "Profitul crește cu X%",
  alertConditionProfitLossPercent: "Pierderea atinge X% (din investiția de referință)",
  alertConditionInvestmentValueAbove: "Valoarea investiției depășește X EUR",
  alertConditionInvestmentValueBelow: "Valoarea investiției scade sub X EUR",
  referenceInvestedAmountForAlert: "Investiția de Referință (pt. %)",
  alertIsActive: "Alertă Activă",
  alertNotActive: "Alertă Inactivă",
  alertLastTriggered: "Ultima Declanșare",
  never: "Niciodată",
  alertCreatedSuccessfully: "Alertă creată cu succes.",
  alertUpdatedSuccessfully: "Alertă actualizată cu succes.",
  alertDeletedSuccessfully: "Alertă ștearsă cu succes.",
  failedToCreateAlert: "Crearea alertei a eșuat.",
  failedToUpdateAlert: "Actualizarea alertei a eșuat.",
  failedToDeleteAlert: "Ștergerea alertei a eșuat.",
  confirmAlertDeletionTitle: "Confirmă Ștergerea Alertei",
  confirmAlertDeletionMessage: "Ești sigur că vrei să ștergi această alertă?",
  noAlertsConfigured: "Nu ai nicio alertă configurată momentan.",
  alertThresholdNumeric: "Pragul trebuie să fie un număr.",
  alertThresholdPositive: "Pragul trebuie să fie un număr pozitiv.",
  alertThresholdPercentageRange: "Procentul trebuie să fie între 0.01 și 1000.",
  alertReferenceAmountForPercentage: "Pentru alerte procentuale, investiția de referință trebuie să fie mai mare ca 0.",
  // FIX: Added missing UI text constant
  cannotCreatePercentageAlertNoInvestment: "Nu poți crea o alertă procentuală fără o investiție activă. Procentajul este calculat pe baza sumei investite în momentul creării alertei.",
  alertTriggeredMessageTitle: "Alertă de Investiție Declanșată!", 
  customizeDashboard: "Personalizează Dashboard",
  saveDashboardPreferences: "Salvează Preferințe și Descarcă",
  resetDashboardToDefault: "Resetează la Implicite",
  dashboardPreferencesSaved: "Preferințele pentru dashboard au fost salvate și fișierul users.json actualizat a fost descărcat. Oferă acest fișier administratorului pentru a actualiza GitHub.",
  dashboardResetSuccess: "Dashboard-ul a fost resetat la configurația implicită. Salvează pentru a persista.",
  widgetDragHandle: "Trage pentru a reordona",
  toggleWidgetVisibility: "Comută vizibilitatea",
  badgesSectionTitle: "Ecusoane Câștigate",
  noBadgesEarned: "Încă nu ai câștigat niciun ecuson. Continuă să investești!",
  badgeEarnedNotificationTitle: "Ecuson Nou Câștigat!",
  badgeEarnedNotificationContent: "Felicitări! Ai câștigat ecusonul: {badgeName}. Vezi-l pe profilul tău.",
  userCycleReportsTitle: "Rapoarte Ciclice de Performanță",
  selectCycleYear: "Selectează Anul",
  selectCycleMonth: "Selectează Luna",
  generateReportButton: "Generează Raport",
  cycleReportFor: "Raport Ciclu", 
  reportPeriod: "Perioada Raportului:",
  balanceAtCycleStart: "Balanța la Începutul Ciclului:",
  depositsInCycle: "Depuneri în Ciclu:",
  withdrawalsInCycle: "Retrageri în Ciclu:",
  grossProfitInCycle: "Profit Brut Generat în Ciclu:",
  feesPaidInCycle: "Taxe Platformă Plătite în Ciclu:",
  netProfitInCycle: "Profit Net Realizat în Ciclu:",
  balanceAtCycleEnd: "Balanța la Sfârșitul Ciclului:",
  percentageGrowthInCycle: "Creștere Procentuală Balanță în Ciclu:",
  noDataForCycleReport: "Nu există suficiente date pentru a genera raportul pentru ciclul selectat.",
  reportPdfGenerating: "Se generează PDF pentru raportul de ciclu...",
  reportPdfGeneratedSuccess: "PDF pentru raportul de ciclu generat cu succes!",
  reportPdfGeneratedError: "Eroare la generarea PDF-ului pentru raportul de ciclu.",
  generatePdfReportButton: "Generează PDF Raport Ciclu",
  helpCenterTitle: "Centru Ajutor",
  faqSectionTitle: "Întrebări Frecvente",
  askGeminiSectionTitle: "Întreabă Asistentul Inteligent",
  askGeminiInputPlaceholder: "Scrie aici întrebarea ta despre platformă...",
  askGeminiButton: "Trimite Întrebarea",
  geminiLoadingResponse: "Gemini procesează răspunsul...",
  geminiNoResults: "Momentan nu am găsit un răspuns specific. Încearcă să reformulezi întrebarea sau consultă un administrator.",
  geminiError: "A apărut o eroare la interogarea Gemini. Te rugăm să încerci mai târziu.",
  geminiApiKeyMissingHelp: "Cheia API pentru Gemini nu este configurată. Funcționalitatea de asistență inteligentă nu este disponibilă.",
  glossarySectionTitle: "Glosar de Termeni / Modul Educațional", 
  feedbackPageTitle: "Trimite Feedback sau Sugestii",
  feedbackFormTitle: "Formular Feedback",
  feedbackCategoryLabel: "Categorie Feedback",
  feedbackCategoryBugReport: "Raportare Problemă Tehnică (Bug)",
  feedbackCategorySuggestion: "Sugestie de Îmbunătățire",
  feedbackCategoryGeneral: "Feedback General",
  feedbackSubjectLabel: "Subiect",
  feedbackSubjectPlaceholder: "Ex: Eroare la afișarea graficului",
  feedbackDescriptionLabel: "Descriere Detaliată",
  feedbackDescriptionPlaceholder: "Descrie cât mai detaliat problema sau sugestia ta...",
  submitFeedbackButton: "Trimite Feedback",
  feedbackSubmittedSuccessfully: "Feedback-ul tău a fost trimis cu succes. Îți mulțumim!",
  failedToSubmitFeedback: "Trimiterea feedback-ului a eșuat. Te rugăm să încerci mai târziu.",
  adminViewFeedbackTitle: "Feedback și Sugestii Utilizatori",
  adminFeedbackTableDate: "Data",
  adminFeedbackTableUser: "Utilizator",
  adminFeedbackTableUserEmail: "Email Utilizator",
  adminFeedbackTableCategory: "Categorie",
  adminFeedbackTableSubject: "Subiect",
  adminFeedbackTableDescription: "Descriere",
  noFeedbackSubmitted: "Nu a fost trimis niciun feedback momentan.",
  adminFeedbackTableStatus: "Status",
  adminFeedbackTableActions: "Acțiuni",
  adminFeedbackFilterByCategory: "Filtrează după Categorie",
  adminFeedbackFilterByStatus: "Filtrează după Status",
  allCategories: "Toate Categoriile",
  allStatuses: "Toate Statusurile",
  feedbackStatusNew: "Nou",
  feedbackStatusInProgress: "În Acțiune",
  feedbackStatusResolved: "Rezolvat",
  markAsInProgress: "Marchează 'În Acțiune'",
  markAsResolved: "Marchează 'Rezolvat'",
  adminPlatformSettingsTitle: "Setări Globale Platformă",
  saveSettingsButton: "Salvează Setările",
  settingsSavedSuccessfully: "Setările platformei au fost salvate cu succes. Fișierul platformSettings.json a fost descărcat.",
  failedToSaveSettings: "Salvarea setărilor a eșuat.",
  platformSettingsDescription: "Modifică aici diverse setări și texte ale platformei. Modificările vor fi reflectate după reîncărcarea datelor din sursă (GitHub).",
  userBacktestingTitle: "Testare Strategii de Investiții (Backtesting)",
  backtestingIntro: "Simulează performanța unei investiții ipotetice pe baza datelor istorice reale ale platformei.",
  simulatedInvestmentAmountLabel: "Suma Investiției Simulate (EUR)",
  goalCreatedSuccessfully: "Obiectiv creat cu succes.",
  failedToCreateGoal: "Crearea obiectivului a eșuat.",
  goalUpdatedSuccessfully: "Obiectiv actualizat cu succes.",
  failedToUpdateGoal: "Actualizarea obiectivului a eșuat.",
  goalAchieved: "Obiectiv atins!",
  goalAchievedMessage: "Felicitări! Ai atins obiectivul: {goalName}.",
  advancedExportXLSXButton: "Export Avansat (XLSX)",
  exportOptionsTitle: "Opțiuni Export",
  exportButton: "Exportă",
  filterByStatus: "Filtrează după Status",
  statusAll: "Toate Statusurile",
  statusActive: "Activ",
  statusInactive: "Inactiv",
  filterByRole: "Filtrează după Rol",
  xlsxExportSuccess: "Fișierul XLSX a fost generat cu succes.",
  xlsxExportFailed: "Generarea fișierului XLSX a eșuat.",
  selectAllTransactionTypes: "Selectează Tot",
  deselectAllTransactionTypes: "Deselectează Tot",
  backtestingInvalidInput: "Datele introduse pentru simulare sunt invalide.",
  backtestingNoDataForPeriod: "Nu există date istorice pentru perioada selectată.",
  backtestingChartLabel: "Valoare Fond Simulat",
  simulationStartDateLabel: "Dată Început Simulare",
  simulationEndDateLabel: "Dată Sfârșit Simulare",
  runSimulationButton: "Rulează Simulare",
  backtestingResultsTitle: "Rezultate Simulare",
  initialSimulatedInvestment: "Investiție Inițială Simulare",
  finalSimulatedBalance: "Balanță Finală Simulare",
  totalSimulatedGrossProfit: "Profit Brut Total Simulat",
  totalSimulatedFeesPaid: "Taxe Totale Simulate",
  totalSimulatedNetProfit: "Profit Net Total Simulat",
  totalSimulatedGrowthPercentage: "Creștere Procentuală Totală",
  simulationPeriod: "Perioada Simulării:",
  backtestingChartTitle: "Evoluția Investiției Simulate",
  backtestingDisclaimer: "Această simulare este o estimare bazată pe date istorice și nu garantează performanțe viitoare. Calculele folosesc ratele de taxă istorice corespunzătoare fiecărei zile.",
  referralCodeGenerationError: "Eroare la generarea codului de recomandare.",
  referralCodeCopied: "Cod copiat în clipboard!",
  referralPageTitle: "Recomandările Mele",
  yourReferralCode: "Codul Tău Unic de Recomandare",
  copyCodeButton: "Copiază Codul",
  referralInstructionsTitle: "Cum Funcționează?",
  referralInstruction1: "Distribuie codul tău unic prietenilor care doresc să investească.",
  referralInstruction2: "Când un prieten se înregistrează folosind codul tău și face prima investiție, amândoi primiți un bonus.",
  referralBenefitsTitle: "Beneficii",
  referralBenefitYou: "Tu primești un bonus bazat pe prima investiție a prietenului tău.",
  referralBenefitFriend: "Prietenul tău primește un bonus de bun venit la prima sa investiție.",
  referralFutureBenefits: "Beneficiile exacte și procentele pot varia. Detaliile vor fi anunțate de administratori.",
  referralsMadeTitle: "Recomandări Finalizate cu Succes",
  referredUserLabel: "Utilizator Recomandat:",
  referralDateLabel: "Data Finalizării:",
  noSuccessfulReferrals: "Încă nu ai recomandări finalizate.",
  eventUpdatedSuccessfully: "Eveniment actualizat cu succes.",
  eventCreatedSuccessfully: "Eveniment creat cu succes.",
  eventDeletedSuccessfully: "Eveniment șters cu succes.",
  adminCalendarTitle: "Calendar Evenimente",
  addNewEvent: "Adaugă Eveniment Nou",
  previousMonth: "Luna Anterioară",
  nextMonth: "Luna Următoare",
  noEventsThisMonth: "Niciun eveniment programat pentru această lună.",
  editEvent: "Modifică Eveniment",
  eventTitleLabel: "Titlu Eveniment",
  eventDateLabel: "Data Eveniment",
  eventTypeLabel: "Tip Eveniment",
  eventTypeSport: "Eveniment Sportiv",
  eventTypeMaintenance: "Mentenanță",
  eventTypeAdminReminder: "Memento Admin",
  eventTypeOther: "Altul",
  eventDescriptionLabel: "Descriere (Opțional)",
  confirmEventDeletionTitle: "Confirmă Ștergerea Evenimentului",
  confirmEventDeletionMessage: "Ești sigur că vrei să ștergi evenimentul '{eventTitle}'? Acțiunea este ireversibilă.",
  noTransactionsFoundForFilters: "Nicio tranzacție găsită pentru filtrele selectate.",
  tableHeaderDate: "Data",
  tableHeaderType: "Tip",
  tableHeaderDescription: "Descriere",
  tableHeaderAmount: "Suma (EUR)",
  tableHeaderStatus: "Status",
  exportToCsvButton: "Exportă în CSV",
  exportToXlsxButton: "Exportă în XLSX",
  exportToPdfButton: "Generează PDF",
  advancedReportsPageTitle: "Rapoarte Avansate",
  filterByTransactionType: "Filtrează după Tipul Tranzacției",
  reportPdfTitle: "Raport Financiar Avansat",
  reportUserLabel: "Utilizator:",
  reportPeriodLabel: "Perioada:",
  reportFiltersAppliedLabel: "Filtre Aplicate:",
  reportGeneratedDateLabel: "Raport generat la:",
  goalCancelledSuccessfully: "Obiectiv anulat cu succes.",
  failedToCancelGoal: "Anularea obiectivului a eșuat.",
  goalStatusActive: "Activ",
  goalStatusCompleted: "Finalizat",
  goalStatusCancelled: "Anulat",
  daysRemaining: "zile rămase:",
  targetDatePassed: "Data țintă a trecut",
  goalCompletedDateLabel: "Finalizat la:",
  userGoalsPageTitle: "Obiectivele Mele de Investiții",
  createNewGoal: "Setează Obiectiv Nou",
  goalNameLabel: "Nume Obiectiv",
  goalNamePlaceholder: "Ex: Fond de vacanță",
  goalTypeLabel: "Tip Obiectiv",
  goalTypeTargetBalance: "Atingere Sold Total",
  goalTypeTargetProfitTotal: "Atingere Profit Total Acumulat",
  goalTargetAmountLabel: "Sumă Țintă (EUR)",
  goalTargetDateLabel: "Data Țintă (Opțional)",
  goalNotesLabel: "Notițe (Opțional)",
  goalStartDateLabel: "Dată Start:",
  confirmGoalCancellationTitle: "Confirmă Anularea Obiectivului",
  confirmGoalCancellationMessage: "Ești sigur că vrei să anulezi obiectivul '{goalName}'? Acesta va fi marcat ca anulat și nu va mai putea fi reactivat.",
  noGoalsSet: "Nu ți-ai setat niciun obiectiv încă. Stabilește o țintă pentru a-ți urmări progresul!",
  watchdogStakeWarning: "Atenție: Miza totală ({totalStake} EUR) reprezintă {stakePercentage}% din banca totală, depășind pragul de {thresholdPercentage}%.",
  watchdogMiddleWarning: "Analiză: Profitul potențial pentru acest 'middle' ({middleProfit} EUR) este foarte mic ({middleProfitPercentage}%) în raport cu riscul total asumat.",
};

export const POPULAR_SPORTS: string[] = [
  'Fotbal',
  'Tenis',
  'Baschet',
  'Volei',
  'Handbal',
  'Hochei pe gheață',
  'Fotbal american',
  'Baseball',
  'eSports',
  'Rugby',
  'Box',
  'MMA',
  'Formula 1',
  'Ciclism',
  'Darts',
  'Snooker',
  'Polo pe apă'
];

export const POPULAR_LEAGUES: string[] = [
  // Fotbal
  'Liga 1 (Romania)',
  'Premier League (Anglia)',
  'La Liga (Spania)',
  'Serie A (Italia)',
  'Bundesliga (Germania)',
  'Ligue 1 (Franta)',
  'UEFA Champions League',
  'UEFA Europa League',
  'Campionatul Mondial',
  'Campionatul European',
  // Baschet
  'NBA (SUA)',
  'Euroliga',
  'Liga Nationala (Romania)',
  'Liga ACB (Spania)',
  // Tenis
  'ATP',
  'WTA',
  'Australian Open',
  'Roland Garros',
  'Wimbledon',
  'US Open',
  // Altele
  'Formula 1',
  'NFL (Fotbal American)',
  'NHL (Hochei pe gheață)',
];

export const POPULAR_SELECTIONS: string[] = [
  // Fotbal
  'Peste 0.5',
  'Peste 1.5',
  'Peste 2.5',
  'Peste 3.5',
  'Sub 0.5',
  'Sub 1.5',
  'Sub 2.5',
  'Sub 3.5',
  'Ambele marchează - Da',
  'Ambele marchează - Nu',
  'Gazde câștigă',
  'Oaspeți câștigă',
  'Egal',
  'Pauză sau Final - Gazde',
  'Pauză sau Final - Oaspeți',
  'Pauză sau Final - Egal',
  'Handicap Asiatic +0.5',
  'Handicap Asiatic +1.5',
  'Handicap Asiatic -0.5',
  'Handicap Asiatic -1.5',
  // Tenis
  'Câștigă Meciul',
  'Peste game-uri',
  'Sub game-uri',
  'Câștigă primul set',
  'Handicap game-uri +1.5',
  'Handicap game-uri -1.5',
  // Baschet
  'Câștigă Meciul (inclusiv prelungiri)',
  'Peste puncte',
  'Sub puncte',
  'Handicap +3.5',
  'Handicap -3.5',
];

export const CHART_COLORS = {
  backgroundColorProfit: 'rgba(74, 222, 128, 0.2)',
  borderColorProfit: '#22c55e',
  backgroundColorBankValue: 'rgba(168, 85, 247, 0.2)',
  borderColorBankValue: '#9333ea',
  backgroundColorInvestedAmount: 'rgba(96, 165, 250, 0.2)',
  borderColorInvestedAmount: '#3b82f6',
  backgroundColorGlobalProfit: 'rgba(239, 68, 68, 0.2)',
  borderColorGlobalProfit: '#ef4444',
  borderColorDailyGrossProfit: '#f59e0b',
  backgroundColorDailyGrossProfit: 'rgba(245, 158, 11, 0.2)',
  backgroundColorUser: 'rgba(59, 130, 246, 0.6)',
  borderColorUser: '#2563eb',
  backgroundColorFee: 'rgba(239, 68, 68, 0.6)',
  borderColorFee: '#dc2626'
};

export const DEFAULT_USER_DASHBOARD_WIDGETS_CONFIG: DashboardWidgetConfig[] = [
  { id: DashboardWidgetType.SUMMARY_INVESTED_AMOUNT, isVisible: true, order: 1 },
  { id: DashboardWidgetType.SUMMARY_TOTAL_PROFIT, isVisible: true, order: 2 },
  { id: DashboardWidgetType.SUMMARY_TOTAL_BALANCE, isVisible: true, order: 3 },
  { id: DashboardWidgetType.SUMMARY_FUND_GROWTH_PERCENTAGE, isVisible: true, order: 4 },
  { id: DashboardWidgetType.INVESTMENT_GOALS_OVERVIEW, isVisible: true, order: 5 },
  { id: DashboardWidgetType.QUICK_ACTIONS, isVisible: true, order: 6 },
  { id: DashboardWidgetType.GEMINI_LUMEN_INSIGHT, isVisible: true, order: 7 },
  { id: DashboardWidgetType.COMMUNITY_CHAT, isVisible: true, order: 8 },
  { id: DashboardWidgetType.PERSONAL_PROFIT_CHART, isVisible: true, order: 9 },
  { id: DashboardWidgetType.FUND_GROWTH_CHART, isVisible: true, order: 10 },
  { id: DashboardWidgetType.RECENT_TRANSACTIONS, isVisible: true, order: 11 },
  { id: DashboardWidgetType.FINANCIAL_PROJECTIONS, isVisible: true, order: 12 },
  { id: DashboardWidgetType.GEMINI_ADVANCED_ANALYSIS, isVisible: false, order: 13 },
  { id: DashboardWidgetType.PLATFORM_FEE_INFO, isVisible: false, order: 14 },
  { id: DashboardWidgetType.PROFIT_SHARE_INFO, isVisible: false, order: 15 },
];

export const AVAILABLE_DASHBOARD_WIDGETS: DashboardWidgetType[] = [
  DashboardWidgetType.SUMMARY_INVESTED_AMOUNT,
  DashboardWidgetType.SUMMARY_TOTAL_PROFIT,
  DashboardWidgetType.SUMMARY_TOTAL_BALANCE,
  DashboardWidgetType.SUMMARY_FUND_GROWTH_PERCENTAGE,
  DashboardWidgetType.INVESTMENT_GOALS_OVERVIEW,
  DashboardWidgetType.PERSONAL_PROFIT_CHART,
  DashboardWidgetType.FUND_GROWTH_CHART,
  DashboardWidgetType.RECENT_TRANSACTIONS,
  DashboardWidgetType.QUICK_ACTIONS,
  DashboardWidgetType.FINANCIAL_PROJECTIONS,
  DashboardWidgetType.GEMINI_ADVANCED_ANALYSIS,
  DashboardWidgetType.GEMINI_LUMEN_INSIGHT,
  DashboardWidgetType.COMMUNITY_CHAT,
  DashboardWidgetType.PLATFORM_FEE_INFO,
  DashboardWidgetType.PROFIT_SHARE_INFO,
];

export const BADGE_DEFINITIONS: Record<BadgeType, { name: string; description: string; icon: React.FC<React.SVGProps<SVGSVGElement>> }> = {
  [BadgeType.FIRST_PROFIT]: { name: "Primul Profit", description: "Ai obținut primul tău profit. Felicitări!", icon: FirstProfitIcon },
  [BadgeType.PLATFORM_VETERAN_30_DAYS]: { name: "Veteran al Platformei", description: "Ești activ pe platformă de peste 30 de zile.", icon: PlatformVeteranIcon },
  [BadgeType.MILESTONE_INVESTMENT_1K]: { name: "Pragul de 1K", description: "Suma ta totală investită a depășit 1,000 EUR.", icon: MilestoneInvestmentIcon },
  [BadgeType.HIGH_ROLLER_SINGLE_INVESTMENT_500]: { name: "Investitor Serios", description: "Ai făcut o singură investiție de peste 500 EUR.", icon: HighRollerIcon },
  [BadgeType.REFERRAL_MADE]: { name: "Ambasador", description: "Ai recomandat cu succes un nou investitor.", icon: UserGroupIcon },
  [BadgeType.WAS_REFERRED]: { name: "Recomandat", description: "Te-ai alăturat platformei printr-o recomandare.", icon: GiftIcon },
  [BadgeType.GOAL_ACHIEVER]: { name: "Realizator de Obiective", description: "Ai atins un obiectiv de investiții. Continuă tot așa!", icon: CheckBadgeIcon },
};

export const BREADCRUMB_NAMES: Record<string, string> = {
  '/': UI_TEXT_ROMANIAN.home,
  '/cum-functioneaza': UI_TEXT_ROMANIAN.howItWorks,
  '/statistici': UI_TEXT_ROMANIAN.statistics,
  '/trophy-room': UI_TEXT_ROMANIAN.trophyRoom,
  '/notifications': UI_TEXT_ROMANIAN.notificationCenter,
  '/help': UI_TEXT_ROMANIAN.helpCenter,
  '/user': UI_TEXT_ROMANIAN.userPanel,
  '/user/dashboard': UI_TEXT_ROMANIAN.myDashboard,
  '/user/investitii': UI_TEXT_ROMANIAN.investments,
  '/user/retrageri': UI_TEXT_ROMANIAN.withdrawals,
  '/user/profil': UI_TEXT_ROMANIAN.profile,
  '/user/alerte': UI_TEXT_ROMANIAN.configureAlerts,
  '/user/reports': UI_TEXT_ROMANIAN.cycleReports,
  '/user/advanced-reports': UI_TEXT_ROMANIAN.advancedReports,
  '/user/goals': UI_TEXT_ROMANIAN.myGoals,
  '/user/bets': UI_TEXT_ROMANIAN.betHistory,
  '/user/feedback': UI_TEXT_ROMANIAN.submitFeedback,
  '/user/referrals': UI_TEXT_ROMANIAN.myReferrals,
  '/user/backtest': UI_TEXT_ROMANIAN.backtestingStrategies,
  '/admin': UI_TEXT_ROMANIAN.adminPanel,
  '/admin/dashboard': UI_TEXT_ROMANIAN.adminDashboard,
  '/admin/market-pulse': UI_TEXT_ROMANIAN.adminMarketPulse,
  '/admin/utilizatori': UI_TEXT_ROMANIAN.manageUsers,
  '/admin/anunturi': UI_TEXT_ROMANIAN.manageAnnouncements,
  '/admin/date': UI_TEXT_ROMANIAN.dataManagement,
  '/admin/aprobari': UI_TEXT_ROMANIAN.pendingRequests,
  '/admin/jurnal': UI_TEXT_ROMANIAN.systemLog,
  '/admin/feedback': UI_TEXT_ROMANIAN.viewFeedback,
  '/admin/settings': UI_TEXT_ROMANIAN.platformSettings,
  '/admin/calendar': UI_TEXT_ROMANIAN.adminCalendar,
};

export const TRANSACTION_TYPE_FRIENDLY_NAMES: Record<TransactionType, string> = {
  [TransactionType.INVESTMENT_REQUEST]: "Cerere Investiție",
  [TransactionType.INVESTMENT_APPROVAL]: "Aprobare Investiție",
  [TransactionType.INVESTMENT_REJECTION]: "Respingere Investiție",
  [TransactionType.WITHDRAWAL_REQUEST]: "Cerere Retragere",
  [TransactionType.WITHDRAWAL_APPROVAL]: "Aprobare Retragere",
  [TransactionType.WITHDRAWAL_REJECTION]: "Respingere Retragere",
  [TransactionType.PROFIT_DISTRIBUTION]: "Distribuire Profit",
  [TransactionType.FEE_COLLECTION]: "Colectare Taxă",
  [TransactionType.DATA_EXPORT]: "Export Date",
  [TransactionType.DATA_IMPORT]: "Import Date",
  [TransactionType.USER_CREATED]: "Utilizator Creat",
  [TransactionType.USER_UPDATED]: "Utilizator Actualizat",
  [TransactionType.USER_DELETED]: "Utilizator Șters",
  [TransactionType.ADMIN_ACTION]: "Acțiune Admin",
  [TransactionType.DAILY_DATA_INPUT]: "Introducere Date Zilnice",
  [TransactionType.ANNOUNCEMENT_CREATED]: "Anunț Creat",
  [TransactionType.ANNOUNCEMENT_UPDATED]: "Anunț Actualizat",
  [TransactionType.ANNOUNCEMENT_DELETED]: "Anunț Șters",
  [TransactionType.USER_ALERT_CREATED]: "Alertă Utilizator Creată",
  [TransactionType.USER_ALERT_UPDATED]: "Alertă Utilizator Actualizată",
  [TransactionType.USER_ALERT_DELETED]: "Alertă Utilizator Ștearsă",
  [TransactionType.USER_ALERT_TRIGGERED]: "Alertă Utilizator Declanșată",
  [TransactionType.GEMINI_BET_RISK_ANALYSIS]: "Analiză Risc Pariu (AI)",
  [TransactionType.USER_DASHBOARD_CONFIG_UPDATED]: "Config. Dashboard Actualizată",
  [TransactionType.BADGE_EARNED]: "Ecuson Câștigat",
  [TransactionType.FEEDBACK_SUBMITTED]: "Feedback Trimis",
  [TransactionType.FEEDBACK_STATUS_UPDATED]: "Status Feedback Actualizat",
  [TransactionType.PLATFORM_SETTINGS_UPDATED]: "Setări Platformă Actualizate",
  [TransactionType.REFERRAL_CODE_GENERATED]: "Cod Recomandare Generat",
  [TransactionType.REFERRAL_LINKED]: "Recomandare Legată",
  [TransactionType.REFERRAL_COMPLETED]: "Recomandare Finalizată",
  [TransactionType.CALENDAR_EVENT_CREATED]: "Eveniment Calendar Creat",
  [TransactionType.CALENDAR_EVENT_UPDATED]: "Eveniment Calendar Actualizat",
  [TransactionType.CALENDAR_EVENT_DELETED]: "Eveniment Calendar Șters",
  [TransactionType.USER_INTERFACE_PREFERENCES_UPDATED]: "Preferințe Interfață Actualizate",
  [TransactionType.COOKIE_CONSENT_UPDATED]: "Consimțământ Cookie Actualizat",
  [TransactionType.GOAL_CREATED]: "Obiectiv Creat",
  [TransactionType.GOAL_UPDATED]: "Obiectiv Actualizat",
  [TransactionType.GOAL_COMPLETED]: "Obiectiv Finalizat",
  [TransactionType.GOAL_CANCELLED]: "Obiectiv Anulat",
  [TransactionType.BET_PLACED]: "Pariu Plasat",
  [TransactionType.BET_UPDATED]: "Pariu Actualizat",
  [TransactionType.BET_DELETED]: "Pariu Șters",
  [TransactionType.BETS_RESOLVED]: "Pariuri Rezolvate",
  [TransactionType.BULK_MESSAGE_SENT]: "Mesaj în Masă Trimis",
};

export const ACCENT_COLOR_PALETTES: Record<AccentPaletteKey, { name: string, baseColor: string }> = {
  'DEFAULT_BLUE': { name: 'Albastru (Implicit)', baseColor: 'primary' },
  'EMERALD_GREEN': { name: 'Verde Smarald', baseColor: 'emerald' },
  'INDIGO_PURPLE': { name: 'Violet Indigo', baseColor: 'indigo' },
  'ROSE_RED': { name: 'Roșu Trandafiriu', baseColor: 'rose' },
  'AMBER_ORANGE': { name: 'Portocaliu Chihlimbar', baseColor: 'amber' },
};

export const INTERFACE_DENSITY_OPTIONS: Record<InterfaceDensity, { name: string }> = {
  [InterfaceDensity.COMFORTABLE]: { name: UI_TEXT_ROMANIAN.densityComfortable },
  [InterfaceDensity.COMPACT]: { name: UI_TEXT_ROMANIAN.densityCompact },
};

export const AVAILABLE_ADMIN_PERMISSIONS: { key: AdminPermission; label: string; description: string; }[] = [
    { key: AdminPermission.CAN_MANAGE_USERS, label: "Poate Gestiona Utilizatori", description: "Creare, modificare, ștergere utilizatori și admini (non-globali)." },
    { key: AdminPermission.CAN_VIEW_STATS, label: "Poate Vizualiza Statistici", description: "Acces la pagina de statistici globale." },
    { key: AdminPermission.CAN_MANAGE_DATA, label: "Poate Gestiona Datele", description: "Acces la pagina de Management Date (Import/Export, editare date zilnice)." },
    { key: AdminPermission.CAN_APPROVE_REQUESTS, label: "Poate Aproba Cereri", description: "Aprobare/respingere cereri de investiții și retrageri." },
    { key: AdminPermission.CAN_VIEW_SYSTEM_LOG, label: "Poate Vizualiza Jurnalul", description: "Acces la jurnalul de evenimente al sistemului." },
    { key: AdminPermission.CAN_MANAGE_ADMIN_PERMISSIONS, label: "Poate Gestiona Permisiuni Admin", description: "Modificarea permisiunilor pentru alți admini (non-globali)." },
    { key: AdminPermission.CAN_USE_GEMINI_ANALYSIS, label: "Poate Utiliza Analiza Gemini", description: "Acces la funcționalitățile de analiză AI cu Gemini." },
    { key: AdminPermission.CAN_MANAGE_ANNOUNCEMENTS, label: "Poate Gestiona Anunțuri", description: "Creare, modificare, ștergere anunțuri pentru toți utilizatorii." },
    { key: AdminPermission.CAN_VIEW_FEEDBACK, label: "Poate Vizualiza Feedback", description: "Acces la feedback-ul trimis de utilizatori." },
    { key: AdminPermission.CAN_MANAGE_PLATFORM_SETTINGS, label: "Poate Gestiona Setări Platformă", description: "Modificarea setărilor globale ale platformei." },
    { key: AdminPermission.CAN_MANAGE_CALENDAR_EVENTS, label: "Poate Gestiona Calendarul", description: "Adăugarea, modificarea și ștergerea evenimentelor din calendarul admin." },
    { key: AdminPermission.CAN_MANAGE_INVESTMENT_GOALS, label: "Poate Gestiona Obiective", description: "Vizualizarea și gestionarea obiectivelor setate de utilizatori (funcționalitate viitoare)." },
];

export const GOAL_TYPE_FRIENDLY_NAMES: Record<GoalType, string> = {
  [GoalType.TARGET_BALANCE]: 'Sold Total Țintă',
  [GoalType.TARGET_PROFIT_TOTAL]: 'Profit Total Acumulat Țintă',
};

export const BET_STATUS_FRIENDLY_NAMES: Record<BetStatus, string> = {
  [BetStatus.PENDING]: 'În Așteptare',
  [BetStatus.WON]: 'Câștigat',
  [BetStatus.LOST]: 'Pierdut',
  [BetStatus.VOID]: 'Anulat (Void)',
  [BetStatus.HALF_WON]: 'Jumătate Câștigat',
  [BetStatus.HALF_LOST]: 'Jumătate Pierdut',
};

export const PREDEFINED_FAQS: FAQItem[] = [
  { question: "Cum pot adăuga fonduri în cont?", answer: "Navighează la secțiunea 'Investiții' din meniu. Acolo vei găsi opțiunile de plată securizate prin Stripe pentru a adăuga fonduri." },
  { question: "Cât durează până când o investiție este aprobată?", answer: "Cererile de investiție sunt de obicei procesate de un administrator în decurs de 24 de ore." },
  { question: "Cum se calculează profitul meu?", answer: "Profitul brut zilnic al băncii este distribuit proporțional între toți investitorii activi, în funcție de ponderea investiției fiecăruia în totalul fondurilor. Din acest profit brut se reține o taxă de platformă, rezultând profitul net care se adaugă la balanța ta." },
  { question: "Ce este taxa de platformă?", answer: "Este o taxă procentuală aplicată doar profitului brut generat. Procentul este dinamic și depinde de numărul total de investitori activi pe platformă. Mai mulți investitori pot duce la o taxă mai mare, dar și la un potențial de profit mai mare per total." },
  { question: "Cum pot retrage bani?", answer: "Mergi la secțiunea 'Retrageri', completează suma dorită și trimite cererea. Un administrator o va procesa în cel mai scurt timp posibil." },
];

export const PREDEFINED_GLOSSARY_TERMS: GlossaryTermItem[] = [
  { term: "Turnover", explanation: "Suma totală a mizelor plasate într-o anumită perioadă (de obicei, o zi). Reprezintă volumul de bani 'rulat' de bancă." },
  { term: "Profit Brut", explanation: "Profitul total generat de pariuri înainte de aplicarea oricăror taxe sau comisioane." },
  { term: "Profit Net", explanation: "Profitul care rămâne după ce din profitul brut se scade taxa de platformă. Acesta este profitul care se adaugă efectiv la balanța ta." },
  { term: "Sold Total Curent", explanation: "Suma totală pe care o deții în platformă la un moment dat. Se calculează ca: Suma Investită + Profitul Total Acumulat." },
  { term: "Backtesting", explanation: "Procesul de testare a unei strategii de investiții pe date istorice reale pentru a evalua cum s-ar fi comportat în trecut. Este un instrument de simulare, nu o garanție a performanței viitoare." },
];

export const MONTH_NAMES_ROMANIAN = ["Ianuarie", "Februarie", "Martie", "Aprilie", "Mai", "Iunie", "Iulie", "August", "Septembrie", "Octombrie", "Noiembrie", "Decembrie"];

export const CALENDAR_EVENT_TYPE_COLORS: Record<CalendarEventType, { bg: string, text: string }> = {
  [CalendarEventType.SPORT_EVENT]: { bg: 'bg-blue-100 dark:bg-blue-900/50', text: 'text-blue-800 dark:text-blue-200' },
  [CalendarEventType.MAINTENANCE]: { bg: 'bg-yellow-100 dark:bg-yellow-900/50', text: 'text-yellow-800 dark:text-yellow-200' },
  [CalendarEventType.ADMIN_REMINDER]: { bg: 'bg-purple-100 dark:bg-purple-900/50', text: 'text-purple-800 dark:text-purple-200' },
  [CalendarEventType.OTHER]: { bg: 'bg-neutral-100 dark:bg-neutral-700/50', text: 'text-neutral-800 dark:text-neutral-200' },
};
